import cv2
import numpy as np

img1=cv2.imread('C:/Users/Ehsan/OneDrive/Desktop/roham coding/open cv/class file/images/img1.jfif',1)
cv2.imshow('image 1',img1)
cv2.waitKey(0)
new_img1=cv2.resize(img1,(200,100))
cv2.imshow('image1 resize',new_img1)
cv2.waitKey(0)
img2=cv2.imread(r'C:\Users\Ehsan\OneDrive\Desktop\roham coding\open cv\class file\images\img2.jfif',1)
cv2.imshow('image 2',img2)
cv2.waitKey(0)
new_img2=cv2.resize(img2,(200,100))
cv2.imshow('image 2 resize',new_img2)
cv2.waitKey(0)
combined_img=cv2.addWeighted(new_img1,0.5,new_img2,0.5,0)
cv2.imshow('combined image',combined_img)
cv2.waitKey(0)
sub_img=cv2.subtract(new_img1,new_img2)
cv2.imshow('subtracted image',sub_img)
cv2.waitKey(0)
kernel=np.ones((3,3),np.uint8)
eroded_img=cv2.erode(img2,kernel)
cv2.imshow('eroded image',eroded_img)
cv2.waitKey(0)
g_blur=cv2.GaussianBlur(img1,(3,3),10)
cv2.imshow('gaussian blur',g_blur)
cv2.waitKey(0)