import cv2
import numpy as np

img1=cv2.imread('C:/Users/Ehsan/OneDrive/Desktop/roham coding/open cv/class file/images/img1.jfif',1)
cv2.imshow('image 1',img1)
cv2.waitKey(0)
new_img1=cv2.resize(img1,(200,100))
cv2.imshow('image1 resize',new_img1)
cv2.waitKey(0)
img2=cv2.imread(r'C:\Users\Ehsan\OneDrive\Desktop\roham coding\open cv\class file\images\img2.jfif',1)
cv2.imshow('image 2',img2)
cv2.waitKey(0)
new_img2=cv2.resize(img2,(200,100))
cv2.imshow('image 2 resize',new_img2)
cv2.waitKey(0)
combined_img=cv2.addWeighted(new_img1,0.5,new_img2,0.5,0)
cv2.imshow('combined image',combined_img)
cv2.waitKey(0)
sub_img=cv2.subtract(new_img1,new_img2)
cv2.imshow('subtracted image',sub_img)
cv2.waitKey(0)
kernel=np.ones((3,3),np.uint8)
eroded_img=cv2.erode(img2,kernel)
cv2.imshow('eroded image',eroded_img)
cv2.waitKey(0)
g_blur=cv2.GaussianBlur(img1,(3,3),10)
cv2.imshow('gaussian blur',g_blur)
cv2.waitKey(0)
m_blur=cv2.medianBlur(img1,(3))
cv2.imshow('median blur',m_blur)
cv2.waitKey(0)
b_blur=cv2.bilateralFilter(img1,(3),5,5)
cv2.imshow('bilateral blur',b_blur)
cv2.waitKey(0)
border=cv2.copyMakeBorder(img2,10,10,10,10,cv2.BORDER_CONSTANT,value=(1,1,1))
cv2.imshow('border',border)
cv2.waitKey(0)
border1=cv2.copyMakeBorder(img2,10,10,10,10,cv2.BORDER_REFLECT)
cv2.imshow('border reflect',border1)
cv2.waitKey(0)
greyscale2=cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
cv2.imshow('greyscale 2',greyscale2)
cv2.waitKey(0)
row,column=img1.shape[0:2]
for i in range(row):
    for o in range(column):
        img1[i][o]=sum(img1[i][o])*0.33
cv2.imshow('greyscale 3',img1)
cv2.waitKey(0)
img1=cv2.imread('C:/Users/Ehsan/OneDrive/Desktop/roham coding/open cv/class file/images/img1.jfif',1)
img1_r=cv2.getRotationMatrix2D((row/2,column/2),angle=90,scale=1)
rimg=cv2.warpAffine(img1,img1_r,(row,column))
cv2.imshow('rotated img', rimg)
cv2.waitKey(0)
img_edge=cv2.Canny(img1,-100,200)
cv2.imshow('edge detection',img_edge)
cv2.waitKey(0)
hsv=cv2.cvtColor(img1,cv2.COLOR_BGR2HSV)
cv2.imshow('hsv',hsv)
cv2.waitKey(0)
start=(0,0)
end=(200,200)
thickness=10
color=(0,0,0)
line_img=cv2.line(img1,start,end,color,thickness)
cv2.imshow('line',line_img)
cv2.waitKey(0)
